name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.144.1
    - name: Build and test with Rake
      run: |
        apt-get install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
